export const firstStepSchema = {
  firstName: {
    placeholder: "First Name",
    requestField: "businessName.personalInfo.firstName",
    value: "",
    error: "",
    required: true,
    section: "",
    validate: "text",
    validation: {},
    minLength: 2,
    maxLength: 20,
    helperText: "Custom error message",
  },
  lastName: {
    placeholder: "Last Name",
    requestField: "businessName.personalInfo.lastName",
    value: "",
    error: "",
    required: true,
    validate: "text",
    minLength: 2,
    maxLength: 20,
  },
  email: {
    placeholder: "Email",
    requestField: "businessName.personalInfo.email",
    value: "",
    error: "",
    validate: "email",
  },
  city: {
    placeholder: "City Name",
    value: "",
    requestField: "businessName.additionalDetails.city",
    error: "",
    validate: "text",
    minLength: 3,
    maxLength: 20,
  },
  agreement: {
    placeholder: "Apartment Name",
    requestField: "businessName.additionalDetails.agreement",
    value: false,
    error: "",
    validation: {
      required: true,
    },
    required: true,
    validate: "checkbox",
    helperText: "Please accept our terms and conditions",
  },
  phone: {
    placeholder: "Phone Name",
    requestField: "businessName.additionalDetails.phone",
    value: "",
    error: "",
    validate: "phone",
    maxLength: 15,
  },
};
